# https://taskfile.dev

version: "3"

includes:
  website:
    taskfile: website
    dir: website

  v2:
    taskfile: v2
    dir: v2
    optional: true
  v3:
    taskfile: v3
    dir: v3
    optional: true

tasks:
  contributors:check:
    cmds:
      - bunx all-contributors-cli check

  contributors:update:
    cmds:
      - go run v3/tasks/contribs/main.go

  contributors:build:
    cmds:
      - bunx all-contributors-cli generate

  format:md:
    cmds:
      - bunx prettier --write "**/*.md"

  format:
    cmds:
      - task: format:md

  syncfork:
    cmds:
      - git remote get-url upstream || (echo "Error: upstream remote not found. Please add it with: git remote add upstream <url>" && exit 1)
      - git fetch upstream
      - git checkout master || git checkout main || (echo "Error: Neither master nor main branch found" && exit 1)
      - git rebase upstream/master || git rebase upstream/main
      - git push --force-with-lease origin master || git push --force-with-lease origin main
      - (git checkout --track origin/v3-alpha 2>/dev/null || git checkout v3-alpha) || echo "v3-alpha branch not found, skipping"
      - git rebase upstream/v3-alpha || echo "Could not rebase v3-alpha"
      - git push --force-with-lease origin v3-alpha || echo "Could not push v3-alpha"

  format-all-md:
    cmds:
      - task: format:md
      - task: website:format:md
      - task: v2:format:md
      # - task: v2:website:format
      - task: v3:format:md
      # - task: v3:website:format:md
