# https://taskfile.dev

version: "3"

includes:
  website:
    taskfile: website
    dir: website

  v2:
    taskfile: v2
    dir: v2
    optional: true
  v3:
    taskfile: v3
    dir: v3
    optional: true

tasks:
  contributors:check:
    cmds:
      - npx -y all-contributors-cli check

  contributors:update:
    cmds:
      - go run v3/tasks/contribs/main.go

  contributors:build:
    cmds:
      - npx -y all-contributors-cli generate

  format:md:
    cmds:
      - npx prettier --write "**/*.md"

  format:
    cmds:
      - task: format:md

  syncfork:
    cmds:
      - git fetch upstream
      - git checkout master
      - git rebase upstream/master
      - git push origin master
      - git checkout v3-alpha
      - git rebase upstream/v3-alpha
      - git push origin v3-alpha

  format-all-md:
    cmds:
      - task: format:md
      - task: website:format:md
      - task: v2:format:md
      # - task: v2:website:format
      - task: v3:format:md
      # - task: v3:website:format:md
