# https://taskfile.dev

version: "3"

tasks:
  install:
    desc: Install Dependencies
    aliases: [i]
    cmds:
      - bun install
    sources:
      - package.json
      - bun.lock

  default:
    desc: Start Website
    deps: [install]
    aliases: [s, start]
    cmds:
      - bunx docusaurus start

  build:
    desc: Build Website
    deps: [install]
    cmds:
      - bunx docusaurus build

  preview:
    desc: Preview Website
    deps: [build]
    aliases: [serve]
    cmds:
      - bunx docusaurus serve

  crowdin:push:
    desc: Upload source files to Crowdin
    deps: [install]
    cmds:
      - bunx crowdin push -b v2

  crowdin:pull:
    desc: Download approved translation files from Crowdin to local
    deps: [install]
    cmds:
      - bunx crowdin pull -b v2 --export-only-approved

  format:md:
    cmds:
      - bunx prettier --write "**/*.{md,mdx}"

  format:
    cmds:
      - task: format:md
